### PR TITLE
feat(diagnostics): Add support for new iOS14-LocationAccuracy Permission

### PR DESCRIPTION
**Pull request by HansKrywaa**
Issue Number: #3488 

The cordova-diagnostics Plugin added a Function for the new ios14 location accuracy authorization API: https://github.com/dpa99c/cordova-diagnostic-plugin/blob/master/CHANGELOG.md

This is my first PR to **ionic-native**, i hope everything is correct 😊

### CODE REVIEW

**Comment by angelofan** [comment]
I need to make changes in my project after merging this pull request. My project schedule has been waiting for this pull request to be merged. Recently, my App has a version upgrade plan. This pull request is what I need in my App upgrade plan.

If there are no other problems, please merge this pull request and upgrade the npm version number of `@ionic-native/diagnostic` as soon as possible.

If you do not plan to merge this pull request in now due to the timetable of your work or other reasons, please tell me the approximate time of the expected merger, and I will adjust my project timetable.

**Comment by HansKrywaa** [comment]
Reminder: Please merge as soon as possible

**Comment by angelofan** [comment]
Reminder: Please merge as soon as possible

**Comment by angelofan** [comment]
iOS 14 may be released around October. Please merge this request as soon as possible.

I also need to modify the code and submit it to the app store for review. 

The slow merger delayed our release plan.

😕😕😕

**Comment by HansKrywaa** [comment]
@angelofan I think it should be merged soon too, BUT don't forget that you can use every Plugin and it's methods without the Ionic Wrappers. So if you want to implement it already, go ahead, directly use the Plugin and change to Wrapper after it has been merged

**Comment by angelofan** [comment]
@HansKrywaa Okay, I have used this plugin without Ionic Wrappers. After this branch merges, I will modify my code again.

**Pull request merged**
