### PR TITLE
HTTP Lib update

### PR DESCRIPTION
**Pull request by troyanskiy**
Hello.

Since the repository `https://github.com/wymsee/cordova-HTTP` is no longer maintained I would like to propose to switch to a fork of the plugin which is maintained nicely.
Thanks.

### CODE REVIEW

**Comment by mburger81** [comment]
this pull request resolves my issue #1883  opened some weeks ago

**Comment by Lestjer** [comment]
after the update when i try to use the plugin, says the HTTP plugin is not installed

**Comment by troyanskiy** [comment]
@Lestjer 
Will check that.
Thanks

**Comment by troyanskiy** [comment]
@Lestjer did you uninstall the old plugin and installed the new one?
`ionic cordova plugin rm cordova-plugin-http`
`ionic cordova plugin add cordova-plugin-advanced-http`

**Comment by Lestjer** [comment]
@troyanskiy 
 I recently installed the plugin in my app, it wasn't an update, and I created a new app to test, but it doesn't work either

**Comment by troyanskiy** [comment]
Indeed. With my old project it works, but if install new from scratch it does not work.
There was the wrong reference in HTTP plugin wrapper.
I have created new PR to fix that.
Thank you @Lestjer for the test!

**Comment by silkimen** [comment]
Hi guys,

I just realised that you are using our version of the HTTP plugin. We are planning to throw out AngularJS (Angular 1.x) support in the next release. See https://github.com/silkimen/cordova-plugin-advanced-http/blob/master/www/angular-integration.js#L4-L87

Will this affect your ionic native integration? I don't think so, but I wanted to ask you first.

**Comment by troyanskiy** [comment]
@silkimen Hi! First of all, thank you for supporting the plugin.
I do not think that it will break something because normally ionic has there are own wrappers.

**Comment by Lestjer** [comment]
@troyanskiy 

I Don't know if I'm missing something, but it still does not work, same message:

```
Native: tried calling HTTP.get, but the HTTP plugin is not installed
Install the HTTP plugin: 'ionic cordova plugin add cordova-plugin-advanced-http'
```

**Comment by troyanskiy** [comment]
@Lestjer the fix has been merged, but not yet pushed to npm.

**Comment by mburger81** [comment]
Hi @silkimen ionic has his own wrapper, as you see now we have your beautiful plugin here :)

**Comment by flowli** [comment]
@troyanskiy Please let us know when the update is available via npm - we need SSL pinning, too :-)

**Comment by troyanskiy** [comment]
Hello @flowli 
Unfortunately, I have no idea when it will be pushed to npm, I'm not an Ionic team member. :)
This question probably should be addressed to @ihadeed .

**Comment by flowli** [comment]
@troyanskiy Thanks for your reply.
@ihadeed Then I ask you :-) Is there any chance if this landing on npm soon? ;-)

**Comment by ihadeed** [comment]
@flowli this PR was published in 4.2.0 https://github.com/ionic-team/ionic-native/releases/tag/v4.2.0

**Comment by troyanskiy** [comment]
@ihadeed I think the subject is about PR #1934

**Comment by CiPhantom** [comment]
i still have same issue

**Comment by jhosilvo** [comment]
> 2020 and am having this issue still.. tried everything.. is there any update? do you recommend anything else?

try call it after platform.ready, it's possible that you are calling the plugin before it's started. 

this.platform.ready().then(() => {

**Pull request merged**
