### PR TITLE
feat(approov-advanced-http) add wrapper for approov advanced http cordova plugin

### PR DESCRIPTION
**Pull request by Shivang8941**

### CODE REVIEW

**Review by danielsogl — CHANGES_REQUESTED** [review]
You have to rename the class name to something like `ApproovHttp` because there is already a Http plugin

**Comment by Shivang8941** [comment]
> 
> 
> You have to rename the class name to something like `ApproovHttp` because there is already a Http plugin

**Comment by Shivang8941** [comment]
> 
> 
> You have to rename the class name to something like `ApproovHttp` because there is already a Http plugin

We want to extend the same plugin that's why we've kept the same name. This way, it will be easier for existing users to migrate to this plugin without a major refactor.

**Comment by danielsogl** [comment]
@Shivang8941 I can understand your point but we dont accept duplicated plugin names. It is also recommended to switch to capacitor and its plugins to handle Http requests etc.

**Comment by Shivang8941** [comment]
> 
> 
> @Shivang8941 I can understand your point but we dont accept duplicated plugin names. It is also recommended to switch to capacitor and its plugins to handle Http requests etc.

For time-being can we only update the plugin name? Will that suffice?

**Comment by Shivang8941** [comment]
@danielsogl Can you please have a look at this again. I've updated the package name.

**Review by danielsogl — APPROVED** [review]

**Pull request merged**
