### PR TITLE
Added postTemplate to BackgroundGeolocationConfig Issue #2285

### PR DESCRIPTION
**Pull request by agenterp**

### CODE REVIEW

**Comment by danielsogl** [comment]
I close this PR because of the upcoming v3 implementation

**Comment by saborpl** [comment]
@danielcregg  v3 implementation of ionic-native? i can't find this...

**Comment by malrok44** [comment]
I think @danielsogl was talking about the v3 of cordova-plugin-mauron85-background-geolocation.
As they mention on their github page, the documentation is for v3 which is still in alpha.
And the postTemplate option is found only in v3.

**Comment by Faizulla-new** [comment]
in backgroundGeoLocation postTemplate is not working

**Pull request closed without merging**
