### PR TITLE
HTTP Plugin reference fix

### PR DESCRIPTION
**Pull request by troyanskiy**
Fixes PR #1921 wrong plugin reference

### CODE REVIEW

**Comment by flowli** [comment]
@ihadeed Hi there, is this already published via npm? Thanks!

**Comment by ihadeed** [comment]
@flowli no, it will be published soon. Tonight, or tomorrow.

**Comment by DayBr3ak** [comment]
Still not published on npm :(

**Comment by troyanskiy** [comment]
Quick fix to all.
1. Open your `node_modules/@ionic-native/http/index.js`
2. Goto line 297 or search for `pluginRef: 'cordovaHTTP',`
3. Replace the line with `pluginRef: 'cordova.plugin.http',`

**Comment by dlmorais-13** [comment]
Another quick fix, but without changing sources at node_modules folder:

Add these two lines in your ```main.ts``` file, before boostrapping AppModule.

```javascript
import { HTTP } from '@ionic-native/http';
HTTP.getPluginRef = () => "cordova.plugin.http";
```

**Comment by yaozuwang** [comment]
I am still getting this error with the reference fix?

**Comment by rizz360** [comment]
`[11:14:26]  console.warn: Native: tried calling HTTP.post, but the HTTP plugin is not installed. 
[11:14:26]  console.warn: Install the HTTP plugin: 'ionic cordova plugin add cordova-plugin-advanced-http' `

Trying to add it:

`cordova plugin add cordova-plugin-advanced-http --save
Plugin "cordova-plugin-advanced-http" already installed on ios.

Saved plugin info for "cordova-plugin-advanced-http" to config.xml
`

**Comment by gustavogr** [comment]
I'm still getting the 'plugin_not_installed' error but only in Android. The reference in the wrapper is already fixed. Any clues?

**Comment by seliestel** [comment]
Also getting this error, in spite of quick-fixes. Does anybody have an alternative to include native Http requests in ionic3? Thanks.

**Comment by elin-y** [comment]
If you are using the latest versions of ionic native and the cordova plugin, the problem it should already be fixed. Did you try to do a clean install? 
```sh
# repeat the following command for all platforms
ionic cordova platform rm android
rm -rf node_modules/ platforms/ plugins/ www/
npm install 
# repeat the following command for all platforms
ionic cordova platform add android
```

**Comment by marutifh** [comment]
I am getting a same error even after trying all the solutions available! 

`Native: tried calling HTTP.setHeader, but the HTTP plugin is not installed.`
`Install the HTTP plugin: 'ionic cordova plugin add cordova-plugin-advanced-http'`

Plugin and node modules versions

`cordova-plugin-advanced-http@1.11.0`
`@ionic-native/core@4.5.3`
`@ionic-native/http@4.5.3`

Even the reference is pointing to the proper plugin.

`    HTTP = __decorate([
        Plugin({
            pluginName: 'HTTP',
            plugin: 'cordova-plugin-advanced-http',
            pluginRef: 'cordova.plugin.http',
            repo: 'https://github.com/silkimen/cordova-plugin-advanced-http',
            platforms: ['Android', 'iOS']
        })
    ], HTTP);
    return HTTP;`

**Comment by diogomgbrito** [comment]
@marutifh did you find a solution?

**Comment by ParikshitSarkar** [comment]
> If you are using the latest versions of ionic native and the cordova plugin, it should already be fixed. Did you try to do a clean install?
> 
> ```shell
> # repeat the following command for all platforms
> ionic cordova platform rm android
> rm -rf node_modules/ platforms/ plugins/ www/
> npm install 
> # repeat the following command for all platforms
> ionic cordova platform add android
> ```

Thanks a lot, this worked for me. I am not getting "plugin not installed" anymore but now I am getting the following error: "Json error". Any idea how I can get around this? Thanks.

**Comment by amrography** [comment]
I had that issue because I was requesting it before `this.platform.ready()`

**Comment by sardapv** [comment]
thanks  man ..i was setting it before ready 

put it in then of platform.ready promise return

**Pull request merged**
