### PR TITLE
feat(firebase-x): add getCurrentUser

### LINKED ISSUE #3356: property 'getCurrentUser' does not exist on type 'FirebaseX'
**I'm submitting a ...**
[x] bug report
[x] feature request
[ ] support request

**Current behavior:**
FirebaseX missing`getCurrentUser` method. Actually, there are a lot of methods are missing.

**Expected behavior:**
All methods described in the plugin documentation should exist.

**Ionic info:** (run `ionic info` from a terminal/cmd prompt and paste output below):

```
Ionic:

   Ionic CLI                     : 6.3.0
   Ionic Framework               : @ionic/angular 5.0.5
   @angular-devkit/build-angular : 0.803.25
   @angular-devkit/schematics    : 8.3.25
   @angular/cli                  : 8.3.25
   @ionic/angular-toolkit        : 2.2.0

Capacitor:

   Capacitor CLI   : 1.5.1
   @capacitor/core : 1.5.1

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v12.13.1 (/Users/ali/.nvm/versions/node/v12.13.1/bin/node)
   npm    : 6.13.7
   OS     : macOS Catalina

```

### PR DESCRIPTION
**Pull request by akshaydwivedi29**
add getCurrentUser method. fixes #3356

### CODE REVIEW

**Comment by danielsogl** [comment]
@akshaydwivedi29 please resolve the conflicts

**Comment by akshaydwivedi29** [comment]
@danielsogl done!

**Comment by akshaydwivedi29** [comment]
@danielsogl will it soon be merged? just confirming. thanks!

**Comment by danielsogl** [comment]
@akshaydwivedi29 The conflicts are still there.

**Comment by akshaydwivedi29** [comment]
@danielsogl it's just one empty line vs my new commit. not able to do anything as git is not recognizing any further changes on the file.

**Comment by dogrusoy** [comment]
Kardeşim ne zaman çözülcek ? Müşteri bekliyor allah allah...

**Pull request merged**
