### PR TITLE
Add cordova-plugin-ionic-webview with convertFileSrc function

### PR DESCRIPTION
**Pull request by jcesarmobile**
Related
https://github.com/ionic-team/ionic-cli/issues/3279

@dwieeb

### CODE REVIEW

**Comment by dwieeb** [comment]
Does it make sense for the URL conversion logic to be in Ionic Native or the Webview Plugin itself? I think the design concept of Ionic Native is to be more of a modern API wrapper around plugin code.

**Comment by dwieeb** [comment]
I think the only purpose to have it here is it's just the "angular" way. People can test it easier, it's more familiar.

Otherwise they'd have to do something like this:

```ts
declare var window: any;
...
window.convertFileSrc()
```

**Comment by jcesarmobile** [comment]
Partly agree with @danielsogl, but that function will be required to make next version of webview plugin to properly work, so we can't tell users they have to add their own convertFileSrc function, we have to provide it

**Comment by dwieeb** [comment]
👉 https://github.com/ionic-team/ionic-native/pull/2549

**Pull request closed without merging**
