### PR TITLE
feat(bluetooth-le): add bluetooth-le plugin

### PR DESCRIPTION
**Pull request by somq**
Plugin wrap around https://github.com/randdusing/cordova-plugin-bluetoothle
A more complete implementation of the BLE API for Android, iOS and Windows than the exisiting one (named ble).

### CODE REVIEW

**Comment by danielsogl** [comment]
Please remove the package-lock.json file from the PR.

**Comment by somq** [comment]
Done

**Comment by somq** [comment]
Fixed it danielsogl

**Comment by laaaaanceeee** [comment]
Yey!!!

**Pull request merged**
