### PR TITLE
fix(secure-storage): add missing function

### LINKED ISSUE #1625: Secure Storage in Ionic Native missing secureDevice function
**I'm submitting a ...**  (check one with "x")
[] bug report
[x ] feature request

**Current behavior:**
The current [SecureStorage](https://github.com/ionic-team/ionic-native/blob/master/src/%40ionic-native/plugins/secure-storage/index.ts) wrapper does not support `secureDevice(successHandler,errorHandler)` function which is present in the [cordova plugin](https://github.com/Crypho/cordova-plugin-secure-storage#users-must-have-a-secure-screen-lock-set) for android platform.

Also check this [stackoverflow question](https://stackoverflow.com/questions/44156522/how-to-open-the-secure-settings-of-the-android-phone-with-my-ionic-2-app)

**Expected behavior:**
Should be able to do:

```
var ss = this.secureStorage.create('myStorage')
                .then((storage: SecureStorageObject) => {
                    storage.set('var', 'toto')
                        .then(
                        () => ss.secureDevice(()=>{},()=>{}),
                        (e) => console.log('error');
                        );
                }).catch((err) => {
                    console.error('The device is not secured');
                })

```
**Steps to reproduce:**

Use the latest ionic blank app and try to access `secureDevice` function.

Apologies if I should have raised this with main ionic repo or at the cordova plugin repo. Please let me know.

### PR DESCRIPTION
**Pull request by danielsogl**
fix #1625

### CODE REVIEW

**Comment by ihadeed** [comment]
Could you please fix the lint issues

**Comment by danielsogl** [comment]
@ihadeed done!

**Comment by danielsogl** [comment]
@ihadeed done!

**Comment by dexterouschen** [comment]
@danielsogl  can you reopen this issue? the newest version of secure storage still haven't solve the inaccessibility of secureDevice(), sure you can access it on SecureStorageObject but this function only matters when the initialization fails, so the Promise rejection should at least include a object with secureDevice() on it. You can probably call it SecureStorageError, that way secureDevice() can be used in the same way as described in the plugin documentation:

https://github.com/Crypho/cordova-plugin-secure-storage#android

```
var ss;
var _init = function () {
    ss = new cordova.plugins.SecureStorage(
        function () {
            console.log('OK');
        },
        function () {
            navigator.notification.alert(
                'Please enable the screen lock on your device. This app cannot operate securely without it.',
                function () {
                    ss.secureDevice(
                        function () {
                            _init();
                        },
                        function () {
                            _init();
                        }
                    );
                },
                'Screen lock is disabled'
            );
        },
        'my_app');
};
_init();
```

**Pull request merged**
