### PR TITLE
PR for fixing missing methods issue #3491

### PR DESCRIPTION
**Pull request by darshanclevertap**

### CODE REVIEW

**Comment by darshanclevertap** [comment]
@danielsogl Can someone help here?

**Comment by darshanclevertap** [comment]
@danielsogl Our clients are waiting for this release. Can we get some response at least? Some sort of an ETA on when will these changes be merged?

**Comment by mhartington** [comment]
@darshanclevertap can you rebase your commits instead of just merging in the changes? The commit history looks a bit messy here. 

Also, Ionic native is community driven, meaning people help out when they can. You do not need to ping Daniel to get his attention.


Clean up the commit history, and it should be good to go from there.

**Comment by darshanclevertap** [comment]
@mhartington Thanks for reaching out. I've updated the code, tried to rebase the commits as well, not sure what was expected of me. Do I need to squash merging commits or just a normal `git rebase -r` ?

**Comment by darshanclevertap** [comment]
@mhartington Any update here?

**Comment by darshanclevertap** [comment]
@mhartington Can we close this soon?

**Comment by mhartington** [comment]
Is the PR correct? Just removing 4 methods from the plugin? `initializeInbox`, `getInboxMessageUnreadCount`, `getInboxMessageCount`, and `showInbox`?

**Comment by darshanclevertap** [comment]
@mhartington Yes, because they were added twice and because of this the methods were unusable

**Pull request closed without merging**
