### PR TITLE
feat(anyline): add plugin

### PR DESCRIPTION
**Pull request by niconaso**
This adds cordova-plugin-anyline plugin. Anyline provides an easy-to-use SDK for applications to enable Optical Character Recognition (OCR) on mobile devices.

### CODE REVIEW

**Comment by niconaso** [comment]
> Please remove the changes from the package-lock.json file

I've just merged the changes with the last commit in master branch. Let me know if this is okey. Thanks!

**Comment by danielsogl** [comment]
You have to remove the file from your PR because as you can see, you committed the package-lock changes again.

**Comment by niconaso** [comment]
> You have to remove the file from your PR because as you can see, you committed the package-lock changes again.

@danielsogl I removed the package-lock file but the CI fails. How can I fix this issue?

**Comment by niconaso** [comment]
> > You have to remove the file from your PR because as you can see, you committed the package-lock changes again.
> 
> @danielsogl I removed the package-lock file but the CI fails. How can I fix this issue?

Could you help me with this? Thanks!

**Comment by danielsogl** [comment]
Done

**Pull request closed without merging**
