### PR TITLE
Update ionic native - HTTP

### PR DESCRIPTION
**Pull request by moathdev**
Dears , 

Many developers complain about the plugin not working and the answer is easy 
just added to app.module.ts :)

### CODE REVIEW

**Comment by raghav-khunger** [comment]
Yes, that comment will be helpful.

**Comment by danielsogl** [comment]
Sorry but this is not necessary. Read the docs and you won't run into that issue: https://ionicframework.com/docs/native/

Checkout the usage section.

> Add Plugins to Your App's Module
> 
> After installing a plugin’s package, add it to your app’s NgModule.

**Comment by moathdev** [comment]
its good and helpful , but can we put it somewhere visible for the new users ?

**Comment by ihadeed** [comment]
It doesn't make sense to include this type of documentation to each plugin manually. The current docs template already includes instructions similar to this.

**Pull request closed without merging**
