### PR TITLE
feat(google-multiple-maps): change for google-map plugin v2-beta

### PR DESCRIPTION
**Pull request by kostap13**
Code for https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/README.md

### CODE REVIEW

**Comment by ihadeed** [comment]
We've had this PR for awhile: https://github.com/driftyco/ionic-native/pull/1166

**Comment by battika** [comment]
Guys, according to the plugin author some recent events are not included in the PR. Can you please have a look into the event list at the following link:

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/ReleaseNotes/v2.0-beta2/README.md

**Comment by danielsogl** [comment]
@battika I will take a look

**Comment by ihadeed** [comment]
@battika this is why I suggested in other comments to wait until v2 is stable before updating our wrapper. 

We can't predict what their final API will look like, and it will be time consuming to try and keep up with them.

**Comment by wf9a5m75** [comment]
Hi, @ihadeed This is Masashi the author of cordova-googlemaps-plugin.

One of the reason of beta is that I have been waiting the ionic wrapper for the v2 since I'm not familiar with ionic. (I noticed this PR today actually)

Another reason is I have been developing the marker clustering feature recently.
After that, I will merge the multiple_maps branch to the master branch (become the stable version).

Technically, the code is stable.
I might add or modify a few changes, but I wont change the api significantly.

**Comment by ihadeed** [comment]
Thanks for the update @wf9a5m75

**Comment by jayeshanandani** [comment]
Can we get in this, please? Not able to use the latest version of Google maps with current ionic native code.

**Comment by fzamperin** [comment]
Would be nice to have latest version of Google Maps with ionic native code, need support for HTMLinfoWindow class.

**Comment by ihadeed** [comment]
Closing this in favour of #1759

**Pull request closed without merging**
