### PR TITLE
fix(indexappcontent): onItemPressed returns observable

### PR DESCRIPTION
**Pull request by NiklasMerz**
Now `onItemPressed` will return an Observable. This should improve adding an event.

Inspired by the 3dTouch plugin function `onHomeIconPressed`.

### CODE REVIEW

**Comment by ihadeed** [comment]
You can use the `@CordovaFunctionOverride` decorator. See example: https://github.com/ionic-team/ionic-native/blob/00c0707dad4fc98974ae2e8c3d720c7a7521e968/src/%40ionic-native/plugins/geofence/index.ts#L98

Sorry the decorator is not documented yet!

**Comment by NiklasMerz** [comment]
I have changed this to the `@CordovaFunctionOverride()`.

**Comment by NiklasMerz** [comment]
Is the the `@CordovaFunctionOverride` decorator working. I have some problems with it?

see also #2028 #2029

**Comment by ihadeed** [comment]
@NiklasMerz it should be working, yes. I will test it soon and apply any fixes if necessary.

**Comment by NiklasMerz** [comment]
@ihadeed I have some trouble with the latest change. I get warnings on the console that the onitemPressed function is not avaivalble. Do you know how the get the decorator working in this scenario?

**Comment by ihadeed** [comment]
@NiklasMerz Found the issue, just pushed a commit to fix it. Update to the latest `@ionic-native/core` and it should be resolved. (Publishing it now, should be live in a few minutes)

**Comment by NiklasMerz** [comment]
Thank you @ihadeed. This fixed the issue for me, too.

**Pull request merged**
