### PR TITLE
fix(web-intent): rename `onNewIntent` to `onIntent`

### PR DESCRIPTION
**Pull request by FdezRomero**
The `onNewIntent` function doesn't exist in `darryncampbell-cordova-plugin-intent`, it's actually called `onIntent`.

Source: https://github.com/darryncampbell/darryncampbell-cordova-plugin-intent/blob/master/www/IntentShim.js#L62

This PR renames `onNewIntent` to `onIntent`, as the implementation was right (should return an Observable). It also removes the previous `onIntent` as it was wrong and shouldn't return `void` anyway.

The change has been tested on device with latest `ionic-angular@3.9.2` and over `@ionic-native/web-intent@4.5.2`.

### CODE REVIEW

**Comment by FdezRomero** [comment]
@danielsogl I forgot to mention that it would be nice to get this ported to 5.0.0, as it has the same issue.

**Comment by FdezRomero** [comment]
Hi there! This PR has been approved, can we get it merged into master for the next release? Thanks!

**Comment by danielsogl** [comment]
Can you resolve the conflicts?

**Comment by FdezRomero** [comment]
@danielsogl I resolved the conflicts, they were because of the new linter rules 😉

**Pull request merged**
