### PR TITLE
feat(preview-any-file): new methods to preview or open files from url, path, assets or base64

### PR DESCRIPTION
**Pull request by mostafa-mansour1**
add new methods to matching the last update of the cordova plugin "cordova-plugin-preview-any-file"

### CODE REVIEW

**Comment by mostafa-mansour1** [comment]
if there is any scheduled time to merge the new wrapper, as the new Cordova plugin has many new features

**Comment by mostafa-mansour1** [comment]
in the section of the install guide 
https://github.com/mostafa-mansour1/previewAnyFile

I add the wrapper as a zip file until it merged here

**Comment by bhandaribhuminpfizer** [comment]
@mostafa-mansour1 waiting for update

**Review by danielsogl — APPROVED** [review]

**Review by danielsogl — APPROVED** [review]

**Comment by Siedlerchr** [comment]
What's the status here? Would be really great to have updated types, because otherwise the plugin usage will throw an error

**Comment by mostafa-mansour1** [comment]
we are waiting for the merge from ionic, you can use the zip file here until it merged 

https://github.com/mostafa-mansour1/previewAnyFile/files/5912855/preview-any-file.zip

**Comment by Siedlerchr** [comment]
@danielsogl  It would be really nice if you could merge this PR!

**Comment by mostafa-mansour1** [comment]
@danielsogl  can you merge this pull request ? the updated plugin don't work with the current version of the wrapper

**Comment by mostafa-mansour1** [comment]
Dear Danielsogl, it's merged only here, but the changes do not appear in https://ionicframework.com/docs/native/preview-any-file and do not appear here also https://www.npmjs.com/package/@ionic-native/preview-any-file
Does it need any change from my side?

**Pull request merged**
