### PR TITLE
fix(email-composer): Aligned function calls with Cordova plugin

### PR DESCRIPTION
**Pull request by ChelloApps**
This is my first attempt at contributing, I have read the guidelines and attempted to follow things as accurately as I can but any feedback to help me in the future is greatly received.

I have been having some major issues with the `cordova-plugin-email-composer` plugin and after no useful feedback on Stackoverflow, Ionic Forum or Github I decided to delve in and see if I could remedy things myself.

I have added the missing functions inline with the existing `cordova-plugin-email-composer` documentation, specifically `hasAccount`, `hasClient` and `getClients`.  I also modified the existing `isAvailable` function to maintain compatibility by combining the `hasAccount` and `hasClient` functions into a single function call for convenience.

Apologies for the `.vscode/settings.json` file making an appearance in the changed files list.

### CODE REVIEW

**Comment by ChelloApps** [comment]
What happens with kind of thing, does it ever get reviewed?

**Comment by ChelloApps** [comment]
OK I have deleted the settings.json file.

Regards
Andy

**Comment by ChelloApps** [comment]
Hi, could you provide feedback on what has happened with this, it looks like I have failed to do something and you've closed it because of that?  However it is very confusing on what exactly I am supposed to do?

I assume because the .vscode settings file was committed in error that has caused the problem, I did delete that file change and thought that was adequate, what did I miss?

**Comment by danielsogl** [comment]
You still committed the package-lock changes so I committed your changes by my self.

**Comment by ChelloApps** [comment]
ah OK sorry my apologies!

**Pull request closed without merging**
