### PR TITLE
feat(adjust): add missing wrappers for cordova api

### PR DESCRIPTION
**Pull request by uerceg**
- `index.ts` wasn't being updated in a while, so adding it with content of all accumulated changes since last update.

### CODE REVIEW

**Comment by danielsogl** [comment]
@uerceg please fix the build errors and resolve the merge conflicts

**Comment by uerceg** [comment]
Hi @danielsogl,

Thanks for the ping. Will be worked on from our end next week most probably. Will update in here once done.

**Comment by uerceg** [comment]
Hi @danielsogl 

We are currently updating our `index.ts` to reflect stand of to-be-released Cordova plugin update. However, I have question regarding your contribution guide, especially this [chapter](https://github.com/ionic-team/ionic-native/blob/master/DEVELOPER.md#testing-your-changes). 

If I run `npm run build`, I get this:

<details>
    <summary>npm run build output</summary>

```
➜  example-ionic-capacitor git:(v4260) ✗ npm run build

> example-ionic-capacitor@0.0.1 build /Users/uerceg/GitHub/cordova_sdk_dev/example-ionic-capacitor
> ng build


Compiling @ionic-native/adjust : module as esm5
✔ Browser application bundle generation complete.
✔ Copying assets complete.
✔ Index html generation complete.

Initial Chunk Files          | Names                     |      Size
vendor.js                    | vendor                    |   4.60 MB
polyfills.js                 | polyfills                 | 252.09 kB
styles.css                   | styles                    |  30.74 kB
main.js                      | main                      |  13.96 kB
runtime.js                   | runtime                   |   9.53 kB

                             | Initial Total             |   4.90 MB

Lazy Chunk Files             | Names                     |      Size
swiper-bundle-95afeea2-js.js | swiper-bundle-95afeea2-js | 200.07 kB
polyfills-core-js.js         | polyfills-core-js         |  92.39 kB
11.js                        | -                         |  72.58 kB
17.js                        | -                         |  71.93 kB
2.js                         | -                         |  63.09 kB
33.js                        | -                         |  56.15 kB
1.js                         | -                         |  47.59 kB
26.js                        | -                         |  46.98 kB
31.js                        | -                         |  37.12 kB
21.js                        | -                         |  32.50 kB
6.js                         | -                         |  32.35 kB
19.js                        | -                         |  32.15 kB
30.js                        | -                         |  31.73 kB
16.js                        | -                         |  30.85 kB
0.js                         | -                         |  29.81 kB
20.js                        | -                         |  26.68 kB
12.js                        | -                         |  26.41 kB
25.js                        | -                         |  26.28 kB
32.js                        | -                         |  24.53 kB
36.js                        | -                         |  23.93 kB
29.js                        | -                         |  23.69 kB
40.js                        | -                         |  21.74 kB
23.js                        | -                         |  21.13 kB
22.js                        | -                         |  21.05 kB
polyfills-dom.js             | polyfills-dom             |  19.47 kB
15.js                        | -                         |  19.39 kB
42.js                        | -                         |  17.78 kB
39.js                        | -                         |  17.33 kB
41.js                        | -                         |  16.95 kB
7.js                         | -                         |  15.95 kB
shadow-css-58508bb5-js.js    | shadow-css-58508bb5-js    |  15.82 kB
4.js                         | -                         |  15.77 kB
24.js                        | -                         |  15.70 kB
10.js                        | -                         |  15.70 kB
input-shims-7a52f98d-js.js   | input-shims-7a52f98d-js   |  15.37 kB
18.js                        | -                         |  15.10 kB
common.js                    | common                    |  13.03 kB
14.js                        | -                         |  12.96 kB
27.js                        | -                         |  12.03 kB
8.js                         | -                         |  11.43 kB
polyfills-css-shim.js        | polyfills-css-shim        |  10.67 kB
9.js                         | -                         |   9.73 kB
35.js                        | -                         |   9.28 kB
34.js                        | -                         |   7.85 kB
37.js                        | -                         |   7.67 kB
home-home-module.js          | home-home-module          |   7.48 kB
28.js                        | -                         |   5.98 kB
keyboard-5742b5da-js.js      | keyboard-5742b5da-js      |   5.97 kB
3.js                         | -                         |   5.88 kB
tap-click-71d2324a-js.js     | tap-click-71d2324a-js     |   5.53 kB
5.js                         | -                         |   3.33 kB
13.js                        | -                         |   3.24 kB
swipe-back-2154c9a7-js.js    | swipe-back-2154c9a7-js    |   2.69 kB
focus-visible-f4ad4f1a-js.js | focus-visible-f4ad4f1a-js |   1.92 kB
38.js                        | -                         |   1.64 kB
status-tap-b46a1b02-js.js    | status-tap-b46a1b02-js    |   1.41 kB

Build at: 2021-03-03T01:20:16.250Z - Hash: c500cb9bf017427b4c75 - Time: 11621ms
```
</details>

However, I see no `dist` directory being created.

Discovered online that one suggestion was to run `npx nuxt generate` instead. If I run that, I get following:

<details>
    <summary>npx nuxt generate output</summary>

```
➜  example-ionic-capacitor git:(v4260) ✗ npx nuxt generate

 WARN  You are using an unsupported version of Node.js (v10.22.0). It is recommended to use the latest LTS version (https://nodejs.org/en/about/releases)               02:23:11


 WARN  When using nuxt generate, you should set target: 'static' in your nuxt.config                                                                                    02:23:12
       👉 Learn more about it on https://go.nuxtjs.dev/static-target

ℹ Production build                                                                                                                                                      02:23:13
ℹ Bundling for server and client side                                                                                                                                   02:23:13
ℹ Target: static                                                                                                                                                        02:23:13

 WARN  No pages directory found in /Users/uerceg/GitHub/cordova_sdk_dev/example-ionic-capacitor. Using the default built-in page.                                       02:23:13

✔ Builder initialized                                                                                                                                                   02:23:13
✔ Nuxt files generated                                                                                                                                                  02:23:13

✔ Client
  Compiled successfully in 5.99s

✔ Server
  Compiled successfully in 504.67ms


Hash: 7939f373eb6d55c14a6a
Version: webpack 4.46.0
Time: 5988ms
Built at: 03/03/2021 2:23:19 AM
                         Asset       Size  Chunks                         Chunk Names
../server/client.manifest.json    7.6 KiB          [emitted]
                    5323fda.js   49.7 KiB       0  [emitted] [immutable]  app
                    5bdba71.js    191 KiB       1  [emitted] [immutable]  commons/app
                    80affce.js   2.29 KiB       2  [emitted] [immutable]  runtime
                    9a3219c.js   4.19 KiB       3  [emitted] [immutable]
                      LICENSES  390 bytes          [emitted]
 + 2 hidden assets
Entrypoint app = 80affce.js 5bdba71.js 5323fda.js

Hash: 9beb8a390fd643c36ee3
Version: webpack 4.46.0
Time: 506ms
Built at: 03/03/2021 2:23:20 AM
               Asset       Size  Chunks             Chunk Names
                1.js    8.3 KiB       1  [emitted]
           server.js   74.5 KiB       0  [emitted]  app
server.manifest.json  167 bytes          [emitted]
 + 2 hidden assets
Entrypoint app = server.js server.js.map
ℹ Generating output directory: dist/                                                                                                                                    02:23:20
ℹ Generating pages                                                                                                                                                      02:23:20

 ERROR   /                                                                                                                                                              02:23:20

Error: Cannot find module 'vue' from '/Users/uerceg/GitHub/cordova_sdk_dev/example-ionic-capacitor'
    at Function.resolveSync [as sync] (/Users/uerceg/.npm/_npx/34409/lib/node_modules/nuxt/node_modules/resolve/lib/sync.js:102:15)
    at /Users/uerceg/.npm/_npx/34409/lib/node_modules/nuxt/node_modules/vue-server-renderer/build.prod.js:1:77685
    at Object.<anonymous> (webpack:/external "vue":1:0)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module.<anonymous> (server.js:560:21)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Object.<anonymous> (server.js:500:18)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at server.js:118:18
    at Object.<anonymous> (server.js:121:10)
    at o (/Users/uerceg/.npm/_npx/34409/lib/node_modules/nuxt/node_modules/vue-server-renderer/build.prod.js:1:77579)
    at /Users/uerceg/.npm/_npx/34409/lib/node_modules/nuxt/node_modules/vue-server-renderer/build.prod.js:1:78172
    at new Promise (<anonymous>)
    at /Users/uerceg/.npm/_npx/34409/lib/node_modules/nuxt/node_modules/vue-server-renderer/build.prod.js:1:78080
    at Object.renderToString (/Users/uerceg/.npm/_npx/34409/lib/node_modules/nuxt/node_modules/vue-server-renderer/build.prod.js:1:81615)
    at SSRRenderer.render (/Users/uerceg/.npm/_npx/34409/lib/node_modules/nuxt/node_modules/@nuxt/vue-renderer/dist/vue-renderer.js:353:38)

✔ Client-side fallback created: 200.html
```
</details>

Do you have any advice how can I proceed with testing the changes?

Cheers
Ugi

**Comment by uerceg** [comment]
Hi @danielsogl 

Just follow up here to check if you have any advices on testing questions I posted above.

Cheers

**Comment by uerceg** [comment]
Hi @danielsogl 

Any updates?

Cheers

**Comment by uerceg** [comment]
Hi @danielsogl 

Any updates on the topic?

Cheers

**Comment by uerceg** [comment]
Hi @danielsogl 

Any updates?

Cheers

**Pull request merged**
