### PR TITLE
fix(firebase-x): indicate callback methods to verifyPhoneNumber

### PR DESCRIPTION
**Pull request by vdias38**
indicate callback methods to verifyPhoneNumber and signInWithCredential functions.

Definition for the non-ionic methods are available as
https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/types/index.d.ts#L120

### CODE REVIEW

**Comment by Sampath-Lokuge** [comment]
Hi @vdias38 Can we have release using this change?

**Comment by vdias38** [comment]
> Hi @vdias38 Can we have release using this change?

I hope, but should wait owners to merge it, or use my branch

**Comment by Sampath-Lokuge** [comment]
Thanks, @vdias38 I'll wait till the official release.

**Comment by CalumMurray** [comment]
Duplicates #3443

**Comment by vdias38** [comment]
> Partially duplicates #3443

Hi @CalumMurray , it's not exactly the same, I don't understand why you use callbacks as arguments and how/why you use them. 
As far as I understand to use callbacks you can use directly the plugin interface. The ionic-native provides an interface to replace callbacks by Promise or Observable, then verifyPhoneNumber for example, could be called as below:

```ts
this.firebaseX.verifyPhoneNumber(phone, this.timeOutDuration)
.then( credential => {...})
.catch(error => {...})
```

Implementation above is compatible with following declaration I've submitted to ionic-native, but not with yours.
```js
  @Cordova({
    callbackOrder: 'reverse'
  })
  verifyPhoneNumber(
    phoneNumber: string,
    timeOutDuration: number,
    fakeVerificationCode?: string
  ): Promise<any> {
    return;
  }
```

**Make sense or do I miss something?**
Following same logic I've added `signOutUser` on this #3458

**Comment by CalumMurray** [comment]
Hi @vdias38, I think you're right. I had assumed they were removed during some build step perhaps as other had left the success/error callbacks in, so I also left them. Thanks for adding `signOutUser()`. Since yours is more complete, I think this can replace my PR #3443

**Pull request merged**
