### PR TITLE
Add getPermissionSubscriptionState

### PR DESCRIPTION
**Pull request by neoassyrian**
Adde d a new method available in the oneSignal Cordova SDK
https://documentation.onesignal.com/docs/cordova-sdk

More methods will probably need to be added

### CODE REVIEW

**Comment by neoassyrian** [comment]
Updated

**Comment by danielsogl** [comment]
@neoassyrian There are still Ci errors (build). Have you tested your changes? 
Have you run the commands `npm run lint `and `npm run build` to test the changes locally?

**Comment by neoassyrian** [comment]
I'm a bit new to this. How can I update the files locally on my dev? 
I tried to update the index.d.ts file installed in my "node_modules" and re-built the project (ionic cordova build) and had no errors. 

Any how to?

**Comment by ihadeed** [comment]
@neoassyrian what do you mean by "update the files locally"? what are you trying to update?

**Comment by neoassyrian** [comment]
I meant when I add the onesignal module in my project and then try to modify the files locally.

**Pull request merged**
