### PR TITLE
Updated documentation to include app.module change

### PR DESCRIPTION
**Pull request by mohammedJ**

### CODE REVIEW

**Comment by danielsogl** [comment]
We don't have to document this because this step is the same for every ionic-native plugin and already documented here: https://ionicframework.com/docs/native/

**Comment by mohammedJ** [comment]
Ok. Not a problem. Just thought its good to have it as sometimes its
overlooked/forgotten

**Comment by janpio** [comment]
Not only that @danielsogl, each plugin links to https://ionicframework.com/docs/native/#Add_Plugins_to_Your_App_Module as step 2 of its installation instructions.

But yeah, people still skip that unfortunately :(

**Comment by mohammedJ** [comment]
@danielsogl , @janpio . Thanks for your time guys. I will close this pull request.

**Pull request closed without merging**
