### PR TITLE
google maps plugin multiple maps

### PR DESCRIPTION
**Pull request by jalescardoso**
More information at: https://github.com/jalescardoso/ionic2-cordova-plugin-googlemaps-v2

### CODE REVIEW

**Comment by John-Luke** [comment]
@ihadeed can you review this?

**Comment by ihadeed** [comment]
@John-Luke waiting for v2.0 to be stable.

**Comment by danielsogl** [comment]
@jalescardoso can you update your PR to add the latest changes?

**Comment by ihadeed** [comment]
I think it's best to wait for v2 to be stable before updating the wrapper. 

Once it's stable, we can review this PR and https://github.com/ionic-team/ionic-native/pull/1424 and update the closest one to the plugins final API then merge it.

**Pull request closed without merging**
