### PR TITLE
feat(tealium): add tealium ionic wrappers

### PR DESCRIPTION
**Pull request by craigrouse**
Added Tealium wrappers
Minor grammar correction in DEVELOPER.md (it's -> its possessive)

### CODE REVIEW

**Comment by craigrouse** [comment]
@danielsogl Just out of curiosity, is there any defined timeline for the 5.0.0 release? I understand these things take time, so I'm not chasing, but would be good to get an indication if possible. Thank you.

**Comment by danielsogl** [comment]
Wait for the next V5 beta or v4 feature release this or next week.

**Comment by craigrouse** [comment]
Thanks @danielsogl!

**Comment by cesarin3134** [comment]
Could you give and idea of when this version will be release ??? 
thanks

**Comment by craigrouse** [comment]
@cesarin3134 it looks like it's been released now. I see the docs up on the Ionic Native site. Any issues, please get in touch via our community (https://community.tealiumiq.com).

**Pull request merged**
