### PR TITLE
feat(preview-any-file): add new methods for preview-any-file cordova

### PR DESCRIPTION
**Pull request by jbagaresgaray**
add new methods to matching the last update of the cordova plugin "cordova-plugin-preview-any-file"

### CODE REVIEW

**Comment by mostafa-mansour1** [comment]
I already have a pull request to update thee wrap from 2nd Feb 

https://github.com/ionic-team/ionic-native/pull/3612

but still didn't merge till now

**Comment by mostafa-mansour1** [comment]
in the section of the install guide 
https://github.com/mostafa-mansour1/previewAnyFile

I add the wrapper as a zip file until it merged here

**Comment by jbagaresgaray** [comment]
> I already have a pull request to update thee wrap from 2nd Feb
> 
> #3612
> 
> but still didn't merge till now

Ohh I see.... you're implementation is base on Observables... Let's wait until Ionic Team gives there feedback...  :(

**Review by danielsogl — APPROVED** [review]

**Comment by mostafa-mansour1** [comment]
oops, this pull request has been approved and the original one conflict with it, what we should do to resolve it, I already wrote the documentation based on observables

**Comment by mostafa-mansour1** [comment]
can i revert the changes to add my code and documentation?

**Comment by jbagaresgaray** [comment]
@mostafa-mansour1 I think Ionic accepts base on Promise response as most of the plugins returns promise as well.. consult @danielsogl instead...

**Comment by mostafa-mansour1** [comment]
ok no problem, but we need at least to fix the docs,

**Pull request merged**
